### ISSUE TITLE
task legacyPraatPitchmarker opens gui

### ISSUE THREAD

**Issue by posttool** [psibre/dfki-spike-data#2]
the first time it asked me for a voice building directory which i closed... 

java process importdatabase remains open. subsequent uses of pitchmarker fail silently! tell me if you want more detail.

will the gui still be required in the some gradle tasks?

**Comment by psibre** [comment]
For the record, this is a pitfall that occurs if the DatabaseImportMain cannot find any `wav/*.wav` under the voicebuilding directory (i.e., `buildDir/`)

**Comment by psibre** [comment]
You'll want to delete the `basenames.lst`, which will otherwise persist and cause an empty build.
